language: java
jdk: oraclejdk8

install: true

deploy:
  provider: heroku
  api_key: 668d314a-7670-4d79-827f-afbad1f8a313
  app: auctionbidme
  run: "mvn clean heroku:deploy"

sudo: false

notifications:
  email:
    recipient:
      -dmitriyshalimov@gmail.com
    on_success: always
    on_failure: always
    email:
      recipient:
        -***@gmail.com
      on_success: always
      on_failure: always