language: java

install: true

sudo: false

addons:
  sonarcloud:
    organization: "dmitriyshalimov-github"
    token:
      secure: "72dba8810cb4a1d6aa235045731da925a13d26b3"

jdk: oraclejdk8


script:
- ./gradlew sonarqube

notifications:
  email:
    recipient:
      -dmitriyshalimov@gmail.com
    on_success: always
    on_failure: always
    email:
      recipient:
        -**8@gmail.com
      on_success: always
      on_failure: always