language: java
jdk: oraclejdk8

install: true

sudo: false

notifications:
  email:
    recipient:
      -dmitriyshalimov@gmail.com
    on_success: always
    on_failure: always
    email:
      recipient:
        -**8@gmail.com
      on_success: always
      on_failure: always