language: java
install: true
jdk: oraclejdk8
sudo: false

addons:
  sonarcloud:
    organization: "dmitriyshalimov-github"
    token:
      secure: "72dba8810cb4a1d6aa235045731da925a13d26b3"




script:
#- "gradle wrapper"
- "gradle sonarqube -X \
     -Dsonar.projectKey=DmitriyShalimov_Deezer \
     -Dsonar.organization=dmitriyshalimov-github \
     -Dsonar.host.url=https://sonarcloud.io \
     -Dsonar.login=72dba8810cb4a1d6aa235045731da925a13d26b3"
- sonar-scanner



notifications:
  email:
    recipient:
      -dmitriyshalimov@gmail.com
    on_success: always
    on_failure: always
    email:
      recipient:
        -**8@gmail.com
      on_success: always
      on_failure: always