version: 0.0
os: linux
files:
  - source: /build/libs/deezer-1.0-SNAPSHOT.war
    destination: /opt/tomcat/
hooks:
  ApplicationStop:
    - location: scripts/stop_application
      timeout: 300
  ApplicationStart:
    - location: scripts/start_application
      timeout: 300
